### ISSUE TITLE
Intraday candle data for expired options is not working. Will it be available?

### ISSUE THREAD

**Issue by PShiw** [samco-sdk/Python-SDK#11]
Intraday candle data for option seems to be working only for non expired options. 

Is it available for expired options as well? Tried it but is not working. Getting below error for expired options.
`
get_intraday_candle_data(symbol_name='NIFTY08JUL2116000CE',exchange="NFO", from_date='2021-07-01 08:09:00')

'{\n  "serverTime": "11/07/21 22:50:05",\n  "msgId": "03fb0b49-9edb-4235-92bc-ed2b7d939761",\n  "status": "Failure",\n  "statusMessage": "No Symbol found for the provided symbol name and exchange."\n}'

`

**Comment by cknmca** [comment]
Absolutely correct. The API currently displays only the non-expiry contracts for options. When querying for stock data, it provides historical intra data for the last 30 days. Attempting to fetch data beyond this period will result in the following error message: "Please limit the date range to 30 days." Thus, the API restricts the date range to ensure that historical intraday data is limited to the last 30 days for stock-related queries.

**Comment by PShiw** [comment]
Closing based on comment.
